<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Mens_Category_Tops_Jacket_Section</name>
   <tag></tag>
   <elementGuidId>6aba8e84-d27e-42a9-bded-3905600ae643</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@href='https://magento.softwaretestingboard.com/men/tops-men/jackets-men.html']//span[contains(text(),'Jackets')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
